[package]
name = "ml"
version = "0.0.1"
authors = [ "wooya <doomsplayer@gmail.com>" ]

[dependencies.matrixrs]
name = "matrixrs"
git = "https://github.com/doomsplayer/matrixrs"
[dependencies.gnuplot]
git = "https://github.com/SiegeLord/RustGnuplot"

[[bin]]
name = "tst"
path = "test/test.rs"
