[package]
name = "machine learning"
version = "0.0.1"
authors = [ "wooya@silic.org" ]

[dependencies.matrixrs]
name = "matrixrs"
git = "https://github.com/doomsplayer/matrixrs.git"

[[lib]]
name = "pagerank"
path = "src/pagerank/mod.rs"
